### PR TITLE
simplifying

### PR DESCRIPTION
**Pull request by slhenry**
re: "If your web site consists of many pages, " almost all will, so it's not worth the qualifier.

I'm not seeing that headings in a page is as relevant here.

### CODE REVIEW

**Comment by iadawn** [comment]
Actually there is a trend for [single page sites](https://onepagelove.com/) that may require the qualifier

**Comment by slhenry** [comment]
oh, I *HATE* those sites ! ! ! I have so much difficulty with them. Personally, I think "more than one method of website navigation" is even *more* important for those types of sites.

**Comment by iadawn** [comment]
OK, I can appreciate that perspective... perhaps it might be helpful to include a suggestion for other types of navigation that is of benefit in these cases. Currently mentioned are "site search or a site map" which wouldn't really be appropriate.

**Comment by iadawn** [comment]
Incorporate the bulk of the suggestion and kept a note of clear headings as a possible orientation approach.

**Pull request closed without merging**
