### PR TITLE
Learn more about accessibility paragraph

### PR DESCRIPTION
**Pull request by slhenry**
I suggest similar re-write of this section on all the pages. :-)

### CODE REVIEW

**Comment by iadawn** [comment]
I am concerned that referring to everything as 'issues' creates a negative impression of the whole thing. I would prefer to use something more like:

> These tips are just some of the important accessibility topics to address when designing websites, but there is always more to consider.  You are encouraged to read the following resources to find out more about accessibility &mdash; why it is important for people with disabilities, for designers, and for organizations; about web accessibility guidelines; and much more.

**Comment by slhenry** [comment]
* I [strongly] do not like "but there is always more"
* The current wording uses "important points" - I'm OK with that.
How about:
<blockquote>
These tips are just some of the important accessibility points to address when designing websites. There are more things to consider. We encourage you to read the following resources to learn more about accessibility — why it is important for people with disabilities, for designers, and for organizations; about web accessibility guidelines; and much more.
</blockquote>

**Comment by iadawn** [comment]
'We encourage' suggests some sort of parental overseeing position that I worry [medium] might come across as a little bit patronising to some.

**Comment by iadawn** [comment]
Suggested alternative included in commit a76366f

**Pull request closed without merging**
