### PR TITLE
Update evaluating.html.erb.md

### PR DESCRIPTION
**Pull request by nitedog**

### CODE REVIEW

**Comment by iadawn** [comment]
This typo was meant to be something more along the lines of 'Run light and early evaluations'. The 'Review processes to incorporate early evaluations' might be more usefully changed to your suggestion?

**Comment by nitedog** [comment]
The two seem very repetitive. If there is a difference between the two, then please differentiate more clearly. Also, you could drop "review processes to" altogether -- there may be no clearly established or documented processes to review. IMO the point is to evaluate early and throughout.

**Comment by iadawn** [comment]
Agreed. I will look at possibly clarifying to one.

Thanks

**Comment by iadawn** [comment]
Addressed

**Pull request closed without merging**
