### PR TITLE
Update authoring.html.erb.md

### PR DESCRIPTION
**Pull request by nitedog**

### CODE REVIEW

**Comment by iadawn** [comment]
It might be a bit confusing to put information in opposition to text, as the information is likely to be text. The aim with this was to use a colloquial and common phrase to highlight the need for simplicity.

**Comment by nitedog** [comment]
The "or" was for you to select one of the terms - sorry, that should have been a comment instead. The point is to clarify the "it" - keep what short?

**Comment by nitedog** [comment]
Please also remove "File download link text should include file type and size" - this is part of "Make the text in links clear" (could actually be an example).

**Comment by iadawn** [comment]
Discussed in weekly meeting. Should be resolved but can be revisited.

**Pull request closed without merging**
