### PR TITLE
copyedit

### PR DESCRIPTION
**Pull request by slhenry**
also, fyi, I'm not sure about "This does not apply for logos, or incidental text, such as text that happens to be in a photograph." but I don't feel strongly enough to comment on it.

### CODE REVIEW

**Comment by iadawn** [comment]
Why parenthesis?

**Comment by slhenry** [comment]
Because it's a parenthetical comment.

**Comment by iadawn** [comment]
I am not sure that it is, as it does not interrupt another phrase or clause. I also think it looks a bit peculiar having this on a separate line in parenthesis. How offended would you be were I to keep the 'Note' structure?

**Comment by slhenry** [comment]
(I am willing to acquiesce on the parenthesis of a stand-alone paragraph.)

The point is that it is just a sidenote. It's not really that important to the tip itself. I agree we should have it, but not for it to get so much attention. I think starting out with "Note" gives it more attention than it needs. Plus it's its own paragraph -- it really stands out.

What about in parenthesis at the end of the main paragraph?

**Comment by iadawn** [comment]
I think I am (possibly irrationally) averse to entire sentences being ensconced in parenthesis. I agree with your point as well though. What about just tagging it on to the end of the main tip and dropping the 'Note that'. So:
 
> "Contrast ratio" is a short version of the more technically correct term "luminance contrast ratio".

As the final sentence?

**Comment by slhenry** [comment]
ok

**Comment by iadawn** [comment]
As agreed, connected contrast ratio tip to main body of tip.

**Pull request closed without merging**
