### PR TITLE
About WCAG box - explaining the links

### PR DESCRIPTION
**Pull request by slhenry**

### CODE REVIEW

**Comment by iadawn** [comment]
Is this much really needed in the side panel? I *seriously* makes this thing long. 
big long side panel

**Comment by slhenry** [comment]
Thanks for mocking it up. Yeah, it looks wayyyy too long there. :-(

I'm just concerned that many folks won't have a clue where those links are going. Lemme try putting it in the intro and let's see what we think of it there...

**Comment by slhenry** [comment]
maybe -- https://github.com/w3c/wai-quick-start/pull/271/files

**Comment by sharronrush** [comment]
I am on the phone with my board of directors meeting but was going to
respond in just that way, Kevin. I think this is far too much for the
sidebar and think it must be quite tersified.

On Wed, Sep 23, 2015 at 4:24 PM, Kevin White <notifications@github.com>
wrote:

> Is this much really needed in the side panel? I *seriously* makes this
> thing long.
> [image: big long side panel]
> <https://cloud.githubusercontent.com/assets/2444840/10059225/bb3adc48-6241-11e5-8147-0659b89e4a4d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/wai-quick-start/pull/270#issuecomment-142733775>.
>



-- 
Sharron Rush | Executive Director | Knowbility.org | @knowbility
*Equal access to technology for people with disabilities*

**Pull request closed without merging**
