### PR TITLE
simplifying BAD description & adding BAD acronym

### PR DESCRIPTION
**Pull request by slhenry**

### CODE REVIEW

**Comment by iadawn** [comment]
Was there a specific reason that the acronym was added in?

**Comment by slhenry** [comment]
Lots of people use "BAD" in conversation. I think it's good to include that. [low-medium]

**Comment by iadawn** [comment]
I think I would prefer to leave it out in this instance... I don't know that it adds that much for the target audience.

**Comment by slhenry** [comment]
sure, ok.

**Pull request closed without merging**
