### PR TITLE
tersify learn more links

### PR DESCRIPTION
**Pull request by slhenry**
I think these links are self-explanatory enough and the additional words just add cognitive load without providing useful additional info.

### CODE REVIEW

**Comment by iadawn** [comment]
If the audience is novice then I think the additional information is required. As extreme examples, W3C Accessibility on it's own says nothing about what that resource provides and Web Accessibility Tutorials says little about what the tutorials cover.

I am not averse to shortening the additional information, or to improving the link text, but I think it needs something more by way of explanation.

**Comment by iadawn** [comment]
The desire to include the text was to entice readers to use the link and give them a brief reason for going there.

Shawn: Agree, I would like them to be more enticing, more focused on the particular audience, and more succinct.

**Comment by iadawn** [comment]
I have made some initial changes to the learn more link explanation text and changed the styling slightly.

**Comment by slhenry** [comment]
/me likes much better!!!
couple suggestions:
1. "Web Accessibility Tutorials — help on developing web content including some guidance on designing, for example, providing alternative text for images"
-> "Web Accessibility Tutorials — includes some guidance related to designing, for example, _providing alternative text for images_"
2. "Accessibility Introduction — includes links to many more helpful resources"
-> "Accessibility Introduction — covers broad issues such as the business case and links to helpful resources"

(with those changes, I'm cool closing this one)

**Comment by iadawn** [comment]
Suggested changes incorporated (with a couple of commas around the 'such as...' part)

**Pull request closed without merging**
