### PR TITLE
decorative image: should->must, expand decorative

### PR DESCRIPTION
**Pull request by davidberman**

### CODE REVIEW

**Comment by iadawn** [comment]
@davidberman couple of points I have some thoughts about:

* The terms 'irrelevant' and 'redundant' as these are a bit too subjective
* The discinction between 'should' and 'must' is probably more specification formal for these tips

Are you seeking to instill a bit more strength behind this particular tip?

**Comment by davidberman** [comment]
Regarding "should" and "must", "should" confuses people... they want to know what they must do, and in this case they must do this for compliance.

I added these additional terms because decorative doesn't take into account all the situations. I think "redundant" is self-explanatory... however it could be explained with an example, such as if a page had a pattern of identical logos, and then only the first would get alternative text and the next would be artifacts. "Irrelevant" is indeed subjective, and unfortunately is by nature up to the content team for a product to interpret. Thoughts?

**Comment by iadawn** [comment]
re: should/must - I would heartily agree for a requirement, but I am a little hesitent for tips of this sort. Simply because there are other instances where there are things that must be done, but the language is deliberately light.

re: redundant - I think I could see that is being slightly troublesome as it could be taken that image choices don't matter and are not important because they are simply redundant. I can think of a couple of designer friends that might take exception if I suggested that ;)

I will bring these topics to the planning meeting on Thursday and it may that they need just a bit of a broader EO discussion.

**Comment by nitedog** [comment]
re: must/should - I suggest avoiding both terms by rewriting the sentence: "Decorative, irrelevant, or redundant images must either have empty alternative text, `alt=''`, or should be presented in <abbr>CSS</abbr> instead of as an img." - > "Use empty alternative text, `alt=''` for decorative images, or include them in the <abbr>CSS</abbr> instead." or such.

re: redundant, irrelevant, and other situations for images that should be ignored - this would need further explanation - for example redundant as in duplicate image vs repeats what is already in the text? (remember: the typical target audience is someone who is very new to accessibility). The tip links to the tutorial that explains this in further detail. I don't think we have the space or attention of the reader to go into this level of detail within the tip. We've followed this approach for other tips too.

**Comment by davidberman** [comment]
I agree with Shadi's approach to vanquishing both the "should" and "must" with the active phrasing suggested above.

Regarding "redundant", I was referring to redundant images... so maybe instead "repeated" would make it clearer that we are referring redundant copies of the same image, as opposed to information that is also expressed in other ways (e.g. in body text)?

**Comment by nitedog** [comment]
But if it is redundant, it should also get empty alt. So we would end up saying "for decorative, repeated, redundant, irrelevant, ... images, do ..." which is more confusing than helpful. I think just give people the most important basic, and clear links to further information if they are interested. Again, in this case we have an entire tutorial specifically on this point, so there is no need to try and pack everything into the tip IMO.

**Comment by iadawn** [comment]
Closing pull request. If there is still an issue, please reopen.

**Pull request closed without merging**
