### PR TITLE
🚩 [Ready for review] French - Tips for Getting Started resources

### PR DESCRIPTION
**Pull request by remibetin**
From @Soahmed2031's #366.

## 🚩 Dependency
- Merge https://github.com/w3c/wai-quick-start/pull/390 before this PR

## Review @remibetin:
- [x] Tips for Getting Started ✅ 
- [x] Tips for Writing ✅ 
- [x] Tips for Designing ✅ 
- [x] Tips for Developing ✅  
- [x] Acknowledgements: can't be added yet: footer template needs update first > moved to #391 

---
Resolves https://github.com/w3c/wai-translations/issues/55, 
Resolves https://github.com/w3c/wai-translations/issues/56, 
Resolves https://github.com/w3c/wai-translations/issues/57, 
Resolves https://github.com/w3c/wai-translations/issues/58

### CODE REVIEW

**Comment by remibetin** [comment]
Thanks @SteveALee it's now working fine !

**Comment by SteveALee** [comment]
@remibetin Excellent. Thanks for updating the PR. We can ignore the Gemfile changes.

@slhenry I think it's over to you for review and merge.

**Comment by remibetin** [comment]
> @slhenry I think it's over to you for review and merge.

Not exactly, we've just fixed the technical side, but now I have to review the content ;)

**Comment by SteveALee** [comment]
>>    @slhenry I think it's over to you for review and merge.
> @SteveALee Not exactly, we've just fixed the technical side, but now I have to review the content ;)

Indeed. I meant "review BEFORE merge" :)

**Comment by remibetin** [comment]
QA done: some adaptations needed, see https://github.com/w3c/wai-quick-start/pull/392

**Pull request merged**
